### ISSUE TITLE
Shopping Cart does not show the discounted price on each item

### ISSUE THREAD

**Issue by MarissaCampa** [MarissaCampa/BulkyBookWeb#24]
# Context
When you add items to the shopping cart, and then click on your shopping cart and displays the items, with a section with `Price x Count`, where the price shown is the regular price, even if we have more than so many items that would create a discount. It's only on the specific line items, because the total does show a total with the discounted price. 

# Reproduction Steps
1. Login to the website
2. Add a number of items to the cart that would create a discount.
3. Go to Shopping Cart.
4. Each individual item has a section with `Price x Count`. The price shown is always the non-bulk price.

# Screenshots

### Product Details page
It shows the discounted price per count (quantity)

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/93a82cad-21c9-4a16-8c3c-724bd3aaeb6c)

### Shopping Cart
The quantity is 53, and the price should be $85 instead of $90 (Total is calculated correctly based on the discount and count)

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/3c88577d-0787-4e2c-ba35-738b627182ae)

**Comment by ohinson01** [comment]
Hi Marissa. 

I found this issue and thought I could take a look at it? I have started to look into contributing to open-source projects and this caught my eye.

**Comment by MarissaCampa** [comment]
Hi @ohinson01, of course, feel free to work on this issue and create a pull request.

**Comment by ohinson01** [comment]
This might take a bit of time. I am currently following the Udemy course to learn more on .NET MVC. Also, the website will not open for me to show the issue, so that is another reason I am following along in the course. If you come up with a solution before I get to this issue, would love to know how you went about resolving it.

**Comment by ohinson01** [comment]
Thank you! I can now view the website. I will recreate your steps to see if I can replicate on my end and then look into the isue further. If I have further questions, will reach back out.

**Comment by ohinson01** [comment]
When I clone your repository on my local drive and run the program, still cannot view it to test out my theory on what is going wrong. It keeps giving me this exception. I will look into why it is doing this, but for now, I will tell you here and let me know what you think. 
<img width="951" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/9c771021-eae9-4bda-8e0c-138e9b4e3ba5">

I was looking to see where the price x count of the item was displaying and found it to be in **Summary.cshtml**.  While looking through the code, I found this section that gave me a clue as to where the price x count was showing when you load the shopping cart. 
<img width="724" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/29a5245d-1f72-4374-b29d-7452514eea80">

I then found the DB context file that let me know where the information was being fetched (ApplicationDbcontext.cs)
<img width="404" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/92d6cdb8-972b-4d53-b494-cca267190f61">

From there, I notice this on line 96. I would like to say that 
<span class="text-muted">@((details.Price * @details.Count).ToString("c")) </span>

I found that the model used in the **Summary.cshtml** file is the ShoppingCartVM. I took a look at the file and found the ShoppingCartList IEnumerable property. 
<img width="482" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/5775e3d4-778a-491a-9769-0591b62e9f90">

I then headed over to where the ShoppingCartList was being called in the CartController.cs file. Scrolling down a ways, I can see how it calculates the price. 
<img width="517" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/d75410ad-e6a2-4004-a5b2-5bbc309c3774">

Looking at the method GetPriceBasedOnQuantity(), I see that it correctly does determine the discount based on the number of books the user buys. 
<img width="530" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/5716b759-61da-4fe4-89a4-8ca7de094fc5">
-----------------------------------------------------------------------------------------------------------------------------------------
Based on my observations, I can see how the OrderTotal is displayed correctly while the discount isn't displaying correctly. I think your issue is in this line of  the **Summary.cshtml**. 
<span class="text-muted">@((details.Price * @details.Count).ToString("c")) </span>

I think it is because there isn't an IF statement to determine what the price should show up as (i.e., like you have in the CartController.cs file). 

That is my observation so far. It was a long explanation, but wanted to be sure I conveyed it thoroughly. Please let me know what you think about this. 

I hope this helps!

**Comment by MarissaCampa** [comment]
Hi @ohinson01 

For your first issue, to be able to run the application locally, you need to have both Stripe and Facebook API keys set in your local project. 

### Stripe and Facebook API keys
The API keys, be set in your BulkyBookProject -> `appsettings.json` file, or BulkyBookProject (Right-click) -> Manage User Secrets -> `secrets.json`. The second option creates the `json` in a hidden file in your local computer. I'm currently using the second option, so that my API keys are not uploaded to this repo, and I'm able to test locally as well. I do recommend you doing the same, so that you don't share your API keys. Once deployed to Azure, I added these keys to the Azure Key Vault (not covered in the course).

The `json` file should have the following fields:
```
{
  "Stripe": {
    "SecretKey": "your_stripe_secret_key",
    "PublishableKey": "your_stripe_publishable_key"
  },
  "FacebookApp": {
    "AppId": "your_facebook_appid",
    "AppSecret": "your_facebook_app_secret"
  }
}
```
These are then called during the app build in `Program.cs`

![image](https://github.com/MarissaCampa/BulkyBookWeb/assets/3021010/e522e1f0-ce2b-468f-852c-3753e63b526a)

Your exception shows that is looking for the `Facebook AppId`, which is shown in the udemy course section [177. Facebook Social Login](https://www.udemy.com/course/complete-aspnet-core-21-course/learn/lecture/37136640)

### Local database

You may also encounter a SQL database problem, you need to make sure that you have a local SQL server and a Database "Bulky"  (covered in the course starting [here](https://www.udemy.com/course/complete-aspnet-core-21-course/learn/lecture/37135598).

## Issue
As per your observations, I think you are going in the right direction! The `GetPriceBasedOnQuantity()` might be able to help getting the correct prices in the ShoppingCartVM before sending it to the View. 

What you can do next, is try to get it working in your local computer, and switch to the branch of this issue https://github.com/MarissaCampa/BulkyBookWeb/tree/24-shopping-cart-does-not-show-the-discounted-price-on-each-item, and commit your code changes/suggestions to the branch, then create a Pull Request so that I can review it.

**Comment by ohinson01** [comment]
@MarissaCampa Ok. Thank you for the explanation on the issue I am having! I will try that and see if I can get my local environment to work. This might take me a bit of time to figure out, but I will be sure to get it working.

**Comment by ohinson01** [comment]
@MarissaCampa 

I got the website to show up in my local environment. I would have gotten to this as soon as possible, but was focused on another task I had in my backlog. 

<img width="937" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/31f75018-afc7-460d-b408-db953dd4a305">

Thanks a bunch for the help in resolving! 

I will now commence implementing my idea and hoping that it works.

**Comment by ohinson01** [comment]
@MarissaCampa 

I resolved the issue. 

So it turns out, I was looking in the wrong cshtml file. Once I ran the application, I realized I was supposed to look at Index.cshtml. I added an IF statement in that section since it looks like it is retrieving the database values (which explains why it did not show the discounted price). I tested with all the books and it seems to be consistent to what the discounted price is now. I will send you the pull request shortly. Let me know if you need anything else. 

<img width="881" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/810db6d5-93f4-4122-9cb4-01c39653da6b">

<img width="848" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/90854d58-cb69-4867-9ce5-bd33730c39ae">

<img width="876" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/0fdffd8b-1001-4421-a7c9-e89f65d7e1ea">

<img width="207" alt="image" src="https://github.com/MarissaCampa/BulkyBookWeb/assets/69820358/d0e2ec16-4e90-44dc-8aed-ee18c6443310">

**Comment by ohinson01** [comment]
PR #35

**Comment by ohinson01** [comment]
Ok! Glad that it worked out on your end. Please tag me anytime you have another issue!
